{{- if eq .Values.postgresql.mode "integrated" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "groombook.fullname" . }}-db-credentials
  labels:
    {{- include "groombook.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ printf "postgres://%s:%s@%s-postgresql:5432/%s" .Values.postgresql.integrated.auth.username (default (randAlphaNum 16) .Values.postgresql.integrated.auth.password) (include "groombook.fullname" .) .Values.postgresql.integrated.auth.database | quote }}
{{- end }}