github.com:
    users:
        groombook-engineer[bot]:
            oauth_token: ghs_znRlNnhuSsNZp0GejabxpkSUqXC9vt27yl3K
    user: groombook-engineer[bot]
    oauth_token: ghs_znRlNnhuSsNZp0GejabxpkSUqXC9vt27yl3K
